apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: docker-clean
  labels:
    name: docker-clean
spec:
  template:
    metadata:
      labels:
        app: docker-clean
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-directory
          hostPath:
            path: /var/lib/docker
      containers:
        - name: docker-clean
          image: opspresso/docker-clean:latest
          env:
            - name: CLEAN_PERIOD
              value: "600"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: false
            - mountPath: /var/lib/docker
              name: docker-directory
              readOnly: false
