apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: docker-clean
  labels:
    name: docker-clean
spec:
  template:
    metadata:
      labels:
        app: docker-clean
    spec:
      containers:
        - name: docker-clean
          image: opspresso/docker-clean:latest
          env:
            - name: CLEAN_PERIOD
              value: "600"
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: false
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
